moved Samtools version check to the right place.

diff --git a/bin/IRFinder b/bin/IRFinder
--- a/bin/IRFinder
+++ b/bin/IRFinder
@@ -254,6 +254,21 @@ fi
 MEMK=`awk '($1 ~ /^MemTotal:/) {print $2}' < /proc/meminfo`
 MEMM=$(($MEMK/1000))
 
+# Check Samtools version
+if [[ "$RUNMODE" != "BAM" && "$RUNMODE" != "FastQ" && "$RUNMODE" != "BuildRefDownload" ]]; then
+	STVERSTR=`samtools --version`
+	STVER=$(echo $STVERSTR|cut -d" " -f2)
+	STVERMAIN=$(echo $STVER|cut -d"." -f1)
+	STVERMINOR=$(echo $STVER|cut -d"." -f2)
+	if [[ ! "$STVERMAIN" -ge 1 ]]; then
+		echo "Error: Samtools $STVER: version too old (>=1.4 required)." >&2
+		exit 1
+	elif [[ ! "$STVERMINOR" -ge 4 ]]; then
+		echo "Error: Samtools $STVER: version too old (>=1.4 required)." >&2
+		exit 1
+	fi
+fi
+
 # Check the compute environment is appropriate for STAR.
 if [[ "$RUNMODE" != "BAM" && "$RUNMODE" != "BuildRefDownload" ]]; then
 	if [ $MEMM -lt 32000 ]; then
